name: casino
services:
  db:
    image: mariadb:11.8.1-ubi9-rc
    container_name: maria_db
    env_file:
      - .env
    ports:
      - "3310:3306"
    volumes:
      - ./../db/queries/:/docker-entrypoint-initdb.d/
      - ./mariadb-custom.cnf:/etc/mysql/conf.d/custom.cnf
      - db_data:/var/lib/mysql
    healthcheck:  
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "dev", "-pcasino"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - secure

  backend:
    build: backend
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy 
    networks:
      - dmz
      - secure
    restart: unless-stopped  
    
  frontend:
    build: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - dmz
      
networks:
  dmz:
    ipam:
      config:
        - subnet: 172.20.0.0/16
  secure:
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  db_data: