name: casino
services:
  frontend:
    image: nginx:1.27.5
    ports:
      - "80:80"
    volumes:
      - ./../frontend/dist/frontend/browser:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - dmz

  db:
    image: mariadb:11.8.1-ubi9-rc
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=casino
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - secure
   
  backend:
    image: node:18
    ports:
      - "3000:3000"
    volumes:
      - ./../backend:/app
    working_dir: /app
    command: "npm run start"
    env_file:
      - db.env
    depends_on:
      - db
    networks:
      - dmz
      - secure

networks:
  dmz:
  secure:

volumes:
  db_data: